title: Shin Ki - Bacatá Aikido 
description: >- # this means to ignore newlines until "baseurl:"
 “Hay dos tipos de ki: el ki común u ordinario y el ki verdadero. 
 
 El ki común es grueso y pesado, el ki verdadero es ligero y versátil. Para un buen desempeño, debes liberarte del ki ordinario y permear tus órganos con el ki verdadero.” 
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
